name: anaconda-client-env
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - tskit>=0.6.3
  - msprime>=1.2.0
  - matplotlib==3.10.3
  - pandas
  - numpy
  - pytest==8.3.5
  - pytest-cov==6.1.1
  - pytest-xdist==3.6.1
  - filelock
