
name: Docs
on:
  pull_request:
  push:
    branches: [main]
    tags:
      - '*'
  merge_group:
jobs:
  Docs:
    permissions:
      contents: read
    uses: petrelharp/tskit.github/.github/workflows/docs.yml@a35059f7617ec56cb61be0538b4f5554c41f66a1
    with:
      install-slim: true
      install-slim-branch: "multitrait"
