
name: Docs
on:
  pull_request:
  push:
    branches: [main]
    tags:
      - '*'
  merge_group:
jobs:
  Docs:
    permissions:
      contents: read
    uses: petrelharp/tskit.github/.github/workflows/docs.yml@e713548d92c7d8ddf45b6f94b7a05efb698d151d
    with:
      install-slim: true
      install-slim-branch: "multitrait"
