
name: Docs
on:
  pull_request:
  push:
    branches: [main]
    tags:
      - '*'
  merge_group:
jobs:
  Docs:
    permissions:
      contents: read
    uses: petrelharp/tskit.github/.github/workflows/docs.yml@e41a80d68523fe86c1cbddd1d4ad2991e699b7c8
    with:
      install-slim: true
      install-slim-branch: "multitrait"
